spring:
  application:
    name: SimplePaymentAPI
  datasource:
    url: jdbc:h2:mem:SimplePaymentAPI
    driver-class-name: org.h2.Driver
    username: localhost
    password: pass
  data:
    rest:
      base-path: /api
  jpa:
    hibernate:
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2
server:
  port: 8082

